import 'dart:math';

class StatusWords {
  StatusWords._();

  static final Random _random = Random();

  static const List<String> words = [
    'Architecting',
    'Baking',
    'Bootstrapping',
    'Brewing',
    'Calculating',
    'Choreographing',
    'Coalescing',
    'Cogitating',
    'Combobulating',
    'Composing',
    'Computing',
    'Concocting',
    'Considering',
    'Contemplating',
    'Cooking',
    'Crafting',
    'Crunching',
    'Deciphering',
    'Deliberating',
    'Elucidating',
    'Envisioning',
    'Fermenting',
    'Flowing',
    'Forging',
    'Harmonizing',
    'Hashing',
    'Hatching',
    'Ideating',
    'Imagining',
    'Improvising',
    'Incubating',
    'Inferring',
    'Infusing',
    'Kneading',
    'Leavening',
    'Manifesting',
    'Marinating',
    'Mulling',
    'Musing',
    'Noodling',
    'Orbiting',
    'Orchestrating',
    'Percolating',
    'Perusing',
    'Pondering',
    'Processing',
    'Proofing',
    'Puzzling',
    'Recombobulating',
    'Ruminating',
    'Seasoning',
    'Simmering',
    'Sketching',
    'Spinning',
    'Sprouting',
    'Stewing',
    'Synthesizing',
    'Tempering',
    'Thinking',
    'Tinkering',
    'Transfiguring',
    'Transmuting',
    'Unfurling',
    'Unravelling',
    'Vibing',
    'Whirring',
    'Whisking',
    'Working',
    'Wrangling',
    'Zesting',
  ];

  static String random() => words[_random.nextInt(words.length)];
}
